using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Microsoft.IdentityModel.Tokens;
using SelfieAWookie.API.UI.Application.DTOs;
using SelfieAWookies.Core.Selfies.Infrastructures.Configurations;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;

namespace SelfieAWookie.API.UI.Controllers
{
    [Route("api/v1/[controller]")]
    [ApiController]
    public class AuthenticateController : ControllerBase
    {
        #region Fields
        private readonly SecurityOptions _option;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IConfiguration _configuration;
        private readonly ILogger<AuthenticateController> _logger;
        #endregion

        #region Constructors
        public AuthenticateController(ILogger<AuthenticateController> logger, UserManager<IdentityUser> userManager, IConfiguration configuration, IOptions<SecurityOptions> option)
        {
            this._userManager = userManager;
            this._configuration = configuration;
            this._option = option.Value;
            this._logger = logger;
        }
        #endregion

        #region Public methods
        [HttpPost]
        [Route("register")]
        public async Task<IActionResult> Register([FromBody] AuthenticateUserDto authenticateUserDto)
        {
            IActionResult result = this.BadRequest();

            var user = new IdentityUser(authenticateUserDto.Login);
            user.Email = authenticateUserDto.Login;
            user.UserName = authenticateUserDto.Name;
            var success = await this._userManager.CreateAsync(user, authenticateUserDto.Password);

            if (success.Succeeded)
            {
                authenticateUserDto.Token = this.GenerateJwtToken(user);
                result = this.Ok(authenticateUserDto);
            }

            return result;
        }


        [HttpPost]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [ProducesResponseType(StatusCodes.Status500InternalServerError)]
        public async Task<IActionResult> Login([FromBody]AuthenticateUserDto authenticateUserDto)
        {
            IActionResult result = this.BadRequest();

            try
            {
                this._logger.LogDebug("This is a test");
                var user = await this._userManager.FindByEmailAsync(authenticateUserDto.Login);
                if (user != null)
                {
                    var verif = await this._userManager.CheckPasswordAsync(user, authenticateUserDto.Password);
                    if (verif)
                    {
                        result = this.Ok(new AuthenticateUserDto()
                        {
                            Login = user.Email,
                            Name = user.UserName,
                            Token = this.GenerateJwtToken(user)
                        }); ;
                    }
                }
            } catch (Exception ex)
            {
                this._logger.LogError("Test error log", ex, authenticateUserDto);
                result = this.Problem("Test error log");
            }

            return result;
        }
        #endregion

        #region Internal methods
        private string GenerateJwtToken(IdentityUser user)
        {
            // Now its ime to define the jwt token which will be responsible of creating our tokens
            var jwtTokenHandler = new JwtSecurityTokenHandler();

            // We get our secret from the appsettings
            var key = Encoding.UTF8.GetBytes(this._option.Key);

            // we define our token descriptor
            // We need to utilise claims which are properties in our token which gives information about the token
            // which belong to the specific user who it belongs to
            // so it could contain their id, name, email the good part is that these information
            // are generated by our server and identity framework which is valid and trusted
            var tokenDescriptor = new SecurityTokenDescriptor
            {
                Subject = new ClaimsIdentity(new[]
                {
                new Claim("Id", user.Id),
                new Claim(JwtRegisteredClaimNames.Sub, user.Email),
                new Claim(JwtRegisteredClaimNames.Email, user.Email),
                // the JTI is used for our refresh token which we will be convering in the next video
                new Claim(JwtRegisteredClaimNames.Jti, Guid.NewGuid().ToString())
            }),
                // the life span of the token needs to be shorter and utilise refresh token to keep the user signedin
                // but since this is a demo app we can extend it to fit our current need
                Expires = DateTime.UtcNow.AddHours(6),
                // here we are adding the encryption alogorithim information which will be used to decrypt our token
                SigningCredentials = new SigningCredentials(new SymmetricSecurityKey(key), SecurityAlgorithms.HmacSha512Signature)
            };

            var token = jwtTokenHandler.CreateToken(tokenDescriptor);

            var jwtToken = jwtTokenHandler.WriteToken(token);

            return jwtToken;
        }
        #endregion
    }
}
